#ifndef __RESOURCES_H__
#define __RESOURCES_H__

#define IDI_LOGO 101
#define IDB_LOGO 102
#define IDR_TRAY_POPUPMENU 103
#define IDM_TRAY_POPUPMENU_EXIT 104
#define IDM_TRAY_POPUPMENU_DISABLE 105
#define IDM_TRAY_POPUPMENU_ENABLE 106

#endif // __RESOURCES_H__
